# Generated by Django 4.2.14 on 2024-07-20 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('house_number', models.CharField(max_length=10, verbose_name='Apartment/House Number')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Name')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street Number')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
