# Generated by Django 4.2.14 on 2024-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
