# Generated by Django 4.2.14 on 2024-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
    ]
