# Generated by Django 4.2.14 on 2024-07-23 13:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_order_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(default=main.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(default=main.models.get_default_time),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
