# Generated by Django 4.2.14 on 2024-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_link',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
