# Generated by Django 4.2.14 on 2024-11-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.CharField(choices=[('6:00 AM', '6:00 AM'), ('8:00 AM', '8:00 AM'), ('10:00 AM', '10:00 AM'), ('6:00 PM', '6:00 PM'), ('8:00 PM', '8:00 PM')], default='6:00 AM', max_length=20),
        ),
    ]
