# Generated by Django 4.2.14 on 2024-11-09 18:26

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_order_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.TimeField(blank=True, choices=[(datetime.time(6, 0), '6:00 AM'), (datetime.time(8, 0), '8:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(18, 0), '6:00 PM'), (datetime.time(20, 0), '8:00 PM')], default=main.models.get_default_time, null=True),
        ),
    ]
